server {

    listen 80;

    root /var/www/html/pages;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /css/ {
        alias /var/www/html/css/;
    }

    location /assets/ {
        alias /var/www/html/assets/;
    }

    location /js/ {
        alias /var/www/html/js/;
    }

    location /uploads/ {
        alias /var/www/html/uploads/;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
    }
}
